# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [28]:
import numpy as np
arr = np.ones((5,5))
arr_6 = arr*6
print(arr_6)
arr_6[1:-1, 1:-1]=0
print('6 on the border and 0 inside in the array-')
print(arr_6)

[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]
6 on the border and 0 inside in the array-
[[6. 6. 6. 6. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 6. 6. 6. 6.]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [61]:
import numpy as np
arr_3 = np.ones((8,8))*9
print('Checkerboard pattern')
arr_3[1::2,::2] = 3
arr_3[::2,1::2] = 3
print(arr_3)

Checkerboard pattern
[[9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [69]:
import numpy as np
arr = np.empty((3,4))
print(arr)
print('*************')
f_arr = np.array([[6,6,6],[6,6,6],[6,6,6]])
print(f_arr)

[[3.56e-322 0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 0.00e+000 0.00e+000]]
*************
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [74]:
import numpy as np
f_arr = np.array([0, 12, 45.21 ,34, 99.91])
print('Farenheit : {}'.format(cel_arr))
c_arr = 5 * f_arr / 9 - 5 * 32 / 9
print('Centigrade : {}'.format(c_arr))

Farenheit : [0, 12, 45.21, 34, 99.91]
Centigrade : [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [12]:
import numpy as np
arr = np.array([1.00000000+0.j, 0.70710678+0.70710678j])
print('Real Numbers : ')
print(arr[0].real)
print(arr[1].real)

print('\n')

print('Imaginary Numbers : ')
print(arr[0].imag)
print(arr[1].imag)


Real Numbers : 
1.0
0.70710678


Imaginary Numbers : 
0.0
0.70710678


Q6. Write the NumPy program to test whether each element of a 1-D

array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [16]:
import numpy as np
arr1 = np.array([ 0,10,20,40,60])
arr2 = np.array([0, 40])

print("Compare each element of array1 and array2")
print(np.in1d(arr1, arr2))

Compare each element of array1 and array2
[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [18]:
import numpy as np
arr1 = np.array([ 0,10,20,40,60])
arr2 = np.array([10, 30, 40])

print("Common values between two arrays :")
print(np.intersect1d(arr1, arr2))

Common values between two arrays :
[10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [58]:
import numpy as np
arr = np.array([[10,10,20,20,30,30]])
print('Original Array : {}'.format(arr))
print('Unique elements of the above array : {}'.format(np.unique(arr)))

arr1 = np.array([[1,1],[2,3]])
print('Original Array : {}'.format(arr1))
print('Unique elements of the above array : {}'.format(np.unique(arr1)))

Original Array : [[10 10 20 20 30 30]]
Unique elements of the above array : [10 20 30]
Original Array : [[1 1]
 [2 3]]
Unique elements of the above array : [1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [59]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))
np.set

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [55]:
import numpy as np
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print('Expected Output :')

print('Repeating 2 times')
print(np.tile(arr, 2))

print('Repeating 3 times')
print(np.tile(arr, 3))

Expected Output :
Repeating 2 times
[1 2 3 4 1 2 3 4]
Repeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [27]:
import numpy as np

arr = np.array([[1,2,3,4,5,6]])

print('Maximum Values : {}'.format(arr.max()))
print('Maximum Values : {}'.format(arr.min()))

Maximum Values : 6
Maximum Values : 1


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [33]:
import numpy as np
a = np.array([1, 2])
b = np.array([4, 5])
print('a > b : {}'.format(a > b))
print('a >= b : {}'.format(a >= b))
print('a < b : {}'.format(a < b))
print('a <= b : {}'.format(a <= b))

a > b : [False False]
a >= b : [False False]
a < b : [ True  True]
a <= b : [ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [47]:
import numpy as np
arr = np.array([[4,6], [2,1]])
print(arr)
print('Sort along the first axis:')
arr.sort(axis=0)
print(arr)
print('Sort along the last axis:')
arr.sort(axis=-1)
print(arr)

[[4 6]
 [2 1]]
Sort along the first axis:
[[2 1]
 [4 6]]
Sort along the last axis:
[[1 2]
 [4 6]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [48]:
import numpy as np
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)

[1 3 2 4 0]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [53]:
import numpy as np
arr = np.array([[0,10,20], [20,30,40]])
arr
print('Values bigger than 10 = {}'.format(arr[arr > 10]))

Values bigger than 10 = [20 20 30 40]


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [54]:
import numpy as np
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


## Great Job!